package ca.bcit.cartoonapp.database.schema;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "CARTOON".
 */
public class Cartoon {

    private Long id;
    private String name;
    private String pictureuri;

    public Cartoon() {
    }

    public Cartoon(Long id) {
        this.id = id;
    }

    public Cartoon(Long id, String name, String pictureuri) {
        this.id = id;
        this.name = name;
        this.pictureuri = pictureuri;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPictureuri() {
        return pictureuri;
    }

    public void setPictureuri(String pictureuri) {
        this.pictureuri = pictureuri;
    }

}
