package ca.bcit.cartoonapp.database.schema;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import ca.bcit.cartoonapp.database.schema.Cartoon;

import ca.bcit.cartoonapp.database.schema.CartoonDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig cartoonDaoConfig;

    private final CartoonDao cartoonDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        cartoonDaoConfig = daoConfigMap.get(CartoonDao.class).clone();
        cartoonDaoConfig.initIdentityScope(type);

        cartoonDao = new CartoonDao(cartoonDaoConfig, this);

        registerDao(Cartoon.class, cartoonDao);
    }
    
    public void clear() {
        cartoonDaoConfig.getIdentityScope().clear();
    }

    public CartoonDao getCartoonDao() {
        return cartoonDao;
    }

}
